theme: jekyll-theme-cayman
title: "likeqydq"
author: "http://fengyh.cn"
description: "爱科技，爱自然，爱生活"
more: "read more »"
url: "http://memleaks.info"
#baseurl: "/contrast" # comment out if in root directory

#comments:
#  disqus: "fengyhack"
#  isso: "comments.mysite.org"

style:
  body: 'white'
  margin: 0%
  padding: 20%
  nav: "#222"
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  uppercase: true

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/fengyhack/", square: true}
#  - weibo: {url: "http://weibo.com/fengyhack", square: true}
  - google-plus: {url: "https://plus.google.com/111357045355121677637", square: true}

paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
permalink: pretty
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed, jekyll-paginate] # include feed plugin (supported by gh-pages)
